all:
  hosts:
    vm1:
      ansible_host: 172.16.237.45
      ansible_user: djella_m
      ansible_ssh_pass: menad
      ansible_become_pass: menad
    vm2:
      ansible_host: 172.16.237.88
      ansible_user: djella_m
      ansible_ssh_pass: menad
      ansible_become_pass: menad
    vm3:
      ansible_host: 172.16.237.146
      ansible_user: djella_m
      ansible_ssh_pass: menad
      ansible_become_pass: menad
  children:
    swarm_manager:
      hosts:
        vm1:
    swarm_workers:
      hosts:
        vm2:
        vm3: